# Generated by Django 2.1.7 on 2019-06-26 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
